// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_B95as1fmB5wBhAduyatDzt_SbN-ireM',
    appId: '1:540965707433:web:97a5e41dadef7601bb53b8',
    messagingSenderId: '540965707433',
    projectId: 'hydrosense-app',
    authDomain: 'hydrosense-app.firebaseapp.com',
    storageBucket: 'hydrosense-app.appspot.com',
    measurementId: 'G-ZDGFEHCXQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQdr8UDNI0Zi8h8AJaCSRqfTZI1rxrLqA',
    appId: '1:540965707433:android:b980a32c0d1017eebb53b8',
    messagingSenderId: '540965707433',
    projectId: 'hydrosense-app',
    storageBucket: 'hydrosense-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMTpoL1eSSiq6aPp31WsbXrtRhW1zL1Dk',
    appId: '1:540965707433:ios:9c672434cf5c770abb53b8',
    messagingSenderId: '540965707433',
    projectId: 'hydrosense-app',
    storageBucket: 'hydrosense-app.appspot.com',
    iosClientId: '540965707433-ih29b0mojrnnc250s9tilf51tpv26b93.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMTpoL1eSSiq6aPp31WsbXrtRhW1zL1Dk',
    appId: '1:540965707433:ios:9c672434cf5c770abb53b8',
    messagingSenderId: '540965707433',
    projectId: 'hydrosense-app',
    storageBucket: 'hydrosense-app.appspot.com',
    iosClientId: '540965707433-ih29b0mojrnnc250s9tilf51tpv26b93.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
